title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://simoneravo.github.io

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/simoneravo.github.io

plugins:
  - jekyll-default-layout


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
